stages:
  - compile
  - unit test
  - docker
  - api test


build jar:
  stage: compile
  image: openjdk:12-alpine
  script:
    - ./gradlew build -x test
  artifacts:
    paths:
      - ./build/libs/

junit:
  stage: unit test
  image: openjdk:12-alpine
  script:
    - ./gradlew test

docker:
  image: docker:latest
  stage: docker
  services:
    - docker:dind
  before_script:
    - echo $CI_BUILD_TOKEN | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"


postman:
  services:
    - name: $CI_REGISTRY/$CI_REGISTRY_IMAGE
      alias: customers
  stage: api test
  image: alpine
  before_script:
    - apk --no-cache add curl
  script:
    - curl http://customers:5000/customers/ | grep "John"